/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package grab.bit.desktop

import grab.bit.desktop.cli.Cli
import grab.bit.desktop.utils.EntryType
import grab.bit.desktop.utils.EntrypointInitializer
import com.github.ajalt.clikt.command.main
import kotlinx.coroutines.runBlocking

/**
 * default launcher
 */

class DefaultAppLauncher {
    suspend fun main(args: Array<String>) {
        /**
         * @see grab.bit.desktop.cli.gui.run.RunGui
         */
        Cli().main(arrayOf(AppArguments.Commands.GUI, AppArguments.Commands.RUN, *args))
    }
}

fun main(args: Array<String>) {
    runBlocking {
        EntrypointInitializer.boot(
            entryType = EntryType.GUI,
        )
        DefaultAppLauncher().main(args)
    }
}
